export const PRICING_TIERS_CLAIM = [
  {
    key: "weekly",
    id: "pro_weekly",
    unit: "week",
    name: "Weekly",
    claimOffer: "Free first week",
    defaultPrice: 5.99,
    originalPrice: 0,
    description: "Perfect for short-term projects.",
    discountId: "dsc_01kn732qx3f2tk2pdpvjj2dav5",
    priceId: "pri_01kn72e7s269tnzcakpvf9fvs5", 
    features: ['Unlimited notes', 'AI Chat', 'Unlimited quizzes & flashcards', 'Quiz notifications'],
  },
  {
    key: "monthly",
    id: "pro_monthly",
    unit: "month",
    name: "Monthly",
    claimOffer: "+42% discount",
    defaultPrice: 11.99,
    originalPrice: 6.99,
    discount: "50% OFF",
    description: "Recommended for ongoing usage.",
    discountId: 'dsc_01kjt6watya70vrj8ctk8mbqpd',
    priceId: "pri_01kn72r9q9rxq8sa54n4xe51w6", 
    features: ['Unlimited notes', 'AI Chat', 'Unlimited quizzes & flashcards', 'Quiz notifications'],
    isPopular: true, // Helper flag for default selection
  },
  {
    key: "annual",
    id: "pro_annual",
    unit: "month",
    name: "Annual",
    defaultPrice: 79.99,
    originalPrice: 65.89, //239 dan endirime claimsiz gelende
    discount: "80% OFF",
    claimOffer: "+2 month free",
    montly_price: 65.89,
    discountId: 'dsc_01kjt7062j64y950pwkfxttr8s',
    priceId: "pri_01kn72whp6q7grp3jhzadkhnny",
    description: "Best value. Save significantly.",
    features: ['Unlimited notes', 'AI Chat', 'Unlimited quizzes & flashcards', 'Quiz notifications'],
  },
];


export const PRICING_TIERS = [
  {
    key: "weekly",
    id: "pro_weekly",
    unit: "week",
    name: "Weekly",
    originalPrice: 5.99,
    description: "Perfect for short-term projects.",
    priceId: "pri_01kn72e7s269tnzcakpvf9fvs5", 
    features: ['Unlimited notes', 'AI Chat', 'Unlimited quizzes & flashcards', 'Quiz notifications'],
  },
  {
    key: "monthly",
    unit: "month",
    id: "pro_monthly",
    name: "Monthly",
    defaultPrice: 34.99,
    originalPrice: 11.99,
    discountId: 'dsc_01kn728x05nvebcaadtwavjyjv',
    discount: "50% OFF",
    description: "Recommended for ongoing usage.",
    priceId: "pri_01kn72g7y1k1was8fy04fnk5pr", 
    features: ['Unlimited notes', 'AI Chat', 'Unlimited quizzes & flashcards', 'Quiz notifications'],
    isPopular: true, // Helper flag for default selection
  },
  {
    key: "annual",
    id: "pro_annual",
    name: "Annual",
    unit: "month",
    defaultPrice: 239.99,
    originalPrice: 79.99, //239 dan endirime claimsiz gelende
    discount: "80% OFF",
    discountId: 'dsc_01kn7312xn4mas8fn4bbybkadp',
    description: "Best value. Save significantly.",
    priceId: "pri_01kn72nntvwtbx9fxpjq1sjyh2",
    features: ['Unlimited notes', 'AI Chat', 'Unlimited quizzes & flashcards', 'Quiz notifications'],
  },
];